[rest_small_refuge]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompt = "Your Party finds a Small Refuge"
success_choice = "REST"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["heal_30"]
retry_effects = []
failure_effects = []
success_messages = ["They Make camp for the night"]
retry_messages = []
failure_messages = ["They Travel onwards"]


[heal_30]
kind = "EncounterEffect/v1"
actor_action = "HEAL"
targets = "ALL"
magnitude = 30
effect_messages = []
extra_effects = []
