[night_time_robbery]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your Party finds a Small Refuge"]
success_choice = "REST"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["heal_40", "night_robbery_500"]
retry_effects = []
failure_effects = []
success_messages = ["They Make camp for the night", "They awaken to discover that 500 Gold has been stolen from your Party!"]
retry_messages = []
failure_messages = ["They Travel onwards"]