[rest_small_refuge]
kind = "Encounters/v1"
encounter_type = "REST"
message = ""
pre_message = "Your Party finds a Small Refuge"
post_message = "They Make camp for the night"
actor_action = "HEAL"
# special_action is None
# additional_events is None
targets = "ALL"
magnitude = 40

[rest_tavern]
kind = "Encounters/v1"
encounter_type = "REST"
message = ""
pre_message = "Your Party finds a Tavern"
post_message = "They rest for an evening"
actor_action = "HEAL"
# special_action is None
# additional_events is None
targets = "ALL"
magnitude = 60

[rest_inn]
kind = "Encounters/v1"
encounter_type = "REST"
message = ""
pre_message = "Your Party finds a Inn"
post_message = "They rest til morning"
actor_action = "HEAL"
# special_action is None
# additional_events is None
targets = "ALL"
magnitude = 90

[rest_village]
kind = "Encounters/v1"
encounter_type = "REST"
message = ""
pre_message = "Your Party finds a Village"
post_message = "They rest for a day"
actor_action = "HEAL"
# special_action is None
# additional_events is None
targets = "ALL"
magnitude = 90

[rest_vassal_keep]
kind = "Encounters/v1"
encounter_type = "REST"
message = "They take a day to rest, and replenish their supplies"
pre_message = "Your Party Finds A Vassal's Keep!"
post_message = "Well rested and well supplied, they travel onwards"
actor_action = "HEAL"
special_action = "AT_MERCHANT"
# additional_events is None
targets = "ALL"
magnitude = 120

[rest_palace]
kind = "Encounters/v1"
encounter_type = "REST"
message = "They take a day to rest, and replenish their supplies"
pre_message = "Your Party Finds A Great City!"
post_message = "Well rested and well supplied, they travel onwards"
actor_action = "HEAL"
special_action = "AT_MERCHANT"
# additional_events is None
targets = "ALL"
magnitude = 150