[rest_small_refuge]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your Party finds a Small Refuge"]
success_choice = "REST"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["heal_30"]
retry_effects = []
failure_effects = []
success_messages = ["They Make camp for the night"]
retry_messages = []
failure_messages = ["They Travel onwards"]

[rest_tavern]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your Party finds a Tavern"]
success_choice = "REST"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["heal_60"]
retry_effects = []
failure_effects = []
success_messages = ["They rest for an evening"]
retry_messages = []
failure_messages = ["They Travel onwards"]

[rest_inn]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your Party finds an Inn"]
success_choice = "REST"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["heal_90"]
retry_effects = []
failure_effects = []
success_messages = ["They rest til morning"]
retry_messages = []
failure_messages = ["They Travel onwards"]

[rest_village]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your Party finds a Village"]
success_choice = "REST"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["heal_90"]
retry_effects = []
failure_effects = []
success_messages = ["They rest til morning"]
retry_messages = []
failure_messages = ["They Travel onwards"]

[rest_vassal_keep]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your Party Finds A Vassal's Keep!"]
success_choice = "REST"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["heal_120", "visit_generic_merchant"]
retry_effects = []
failure_effects = []
success_messages = ["They take a day to rest, and replenish their supplies", "Well rested and well supplied, they travel onwards",]
retry_messages = []
failure_messages = ["They Travel onwards"]

[rest_palace]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your Party Finds A Great City!"]
success_choice = "REST"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["heal_120", "visit_generic_merchant"]
retry_effects = []
failure_effects = []
success_messages = ["They take a day to rest, and replenish their supplies", "Well rested and well supplied, they travel onwards",]
retry_messages = []
failure_messages = ["They Travel onwards"]
