[surprise_attack]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your party Encounters A Strange Figure!"]
success_choice = "GREET"
# retry_choice = None
failure_choice = "ATTACK"
success_effects = ["damage_30"]
retry_effects = []
failure_effects = ["damage_30"]
success_messages = ["The Figure blasts your party with an Arcane Bolt and vanishes into a Flash of Light!"]
retry_messages = []
failure_messages = ["The Figure blasts your party with an Arcane Bolt and vanishes into a Flash of Light!"]

[surprise_heal]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your party Encounters A Strange Figure!"]
success_choice = "GREET"
# retry_choice = None
failure_choice = "ATTACK"
success_effects = ["heal_30"]
retry_effects = []
failure_effects = ["damage_30"]
success_messages = ["The Figure heals your party and vanishes into the darkness!"]
retry_messages = []
failure_messages = ["The Figure blasts your party with an Arcane Bolt and vanishes into a Flash of Light!"]

[surprise_chest]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your party find a small treasure chest"]
success_choice = "OPEN"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["gold_100"]
retry_effects = []
failure_effects = []
success_messages = ["Upon opening it reveals 100 gold"]
retry_messages = []
failure_messages = []

[surprise_bomb]
kind = "Encounters/v1"
primary_encounter = true
special_encounter = false
# next_encounter = None
prompts = ["Your party find a small treasure chest"]
success_choice = "OPEN"
# retry_choice = None
failure_choice = "LEAVE"
success_effects = ["damage_150"]
retry_effects = []
failure_effects = []
success_messages = ["Upon opening an explosion is triggered and everyone is thrown backwards"]
retry_messages = []
failure_messages = []
