["Demons"]
plural_name = "Demons"
group_name = "Band"
weight_class = "MEDIUM"

[["Demons.variant_lists_data.lesser_variants_data"]]
name = "Demon Fiendling"
health = 90
strength = 3
intellect = 5
agility = 6
luck = 1
attack_name = "Soul Decay Burst"
is_special = false

[["Demons.variant_lists_data.common_variants_data"]]
name = "Abyssal Demon"
health = 130
strength = 4
intellect = 7
agility = 3
luck = 2
attack_name = "Soul Decay Orb"
is_special = false

[["Demons.variant_lists_data.greater_variants_data"]]
name = "Demon Archfiend"
health = 180
strength = 5
intellect = 9
agility = 4
luck = 1
attack_name = "Soul Decay Wave"
is_special = false