["dire_wolves"]
kind = "EnemySet/v1"
plural_name = "Dire Wolves"
group_name = "Pack"
weight_class = "MEDIUM"
set_type = "STANDARD"
# key_enemy = None
enemy_ids = [
    "young_dire_wolf",
    "dire_wolf",
    "alpha_dire_wolf",
]

["young_dire_wolf"]
name = "Young Dire Wolf"
kind = "Enemy/v1"
variant_grade = "LESSER"
health = 75
strength = 4
intellect = 3
agility = 8
luck = 6
attack_name = "Wolf Bite"
is_special = false

["dire_wolf"]
name = "Dire Wolf"
variant_grade = "COMMON"
kind = "Enemy/v1"
health = 100
strength = 5
intellect = 3
agility = 8
luck = 6
attack_name = "Wolf Bite"
is_special = false

["alpha_dire_wolf"]
name = "Alpha Dire Wolf"
variant_grade = "GREATER"
kind = "Enemy/v1"
health = 150
strength = 6
intellect = 4
agility = 8
luck = 6
attack_name = "Wolf Bite"
is_special = false