["feral_imps"]
kind = "EnemySet/v1"
plural_name = "Feral Imps"
group_name = "Mischief"
weight_class = "SMALL"
set_type = "STANDARD"
enemy_ids = [
    "young_feral_imp",
    "feral_imp",
    "painted_feral_imp",
]

["young_feral_imp"]
kind = "Enemy/v1"
variant_grade = "LESSER"
name = "Young Feral Imp"
health = 60
strength = 1
intellect = 3
agility = 4
luck = 6
attack_name = "Weak Fireball"
is_special = false

["feral_imp"]
kind = "Enemy/v1"
variant_grade = "COMMON"
name = "Feral Imp"
health = 80
strength = 3
intellect = 5
agility = 5
luck = 3
attack_name = "Fireball"
is_special = false

["painted_feral_imp"]
kind = "Enemy/v1"
variant_grade = "GREATER"
name = "Painted Feral Imp"
health = 120
strength = 5
intellect = 6
agility = 4
luck = 4
attack_name = "Empowered Fireball"
is_special = false