["ice_drakes"]
kind = "EnemySet/v1"
plural_name = "Ice Drakes"
group_name = "Clan"
weight_class = "LARGE"
set_type = "STANDARD"
enemy_ids = [
    "juvenile_ice_drake",
    "ice_drake",
    "ice_drake_matriarch",
]

["juvenile_ice_drake"]
kind = "Enemy/v1"
variant_grade = "LESSER"
name = "Juvenile Ice Drake"
health = 175
strength = 7
intellect = 5
agility = 6
luck = 8
attack_name = "Blizzard Breath"
is_special = false

["ice_drake"]
kind = "Enemy/v1"
variant_grade = "COMMON"
name = "Ice Drake"
health = 250
strength = 8
intellect = 6
agility = 6
luck = 8
attack_name = "Blizzard Breath"
is_special = false

["ice_drake_matriarch"]
kind = "Enemy/v1"
variant_grade = "GREATER"
name = "Ice Drake Matriarch"
health = 325
strength = 9
intellect = 7
agility = 6
luck = 8
attack_name = "Blizzard Breath"
is_special = false