[penultimate_boss]
kind = "Enemy/v1"
name = "The Great Wizard Algolon"
variant_grade = "SPECIAL"
health = 600
strength = 5
intellect = 12
agility = 5
luck = 6
attack_name = "Cosmic Collision"
is_special = true