[ultimate_boss]
kind = "Enemy/v1"
name = "Fortranus the Ancient One"
variant_grade = "SPECIAL"
health = 1000
strength = 14
intellect = 10
agility = 7
luck = 6
attack_name = "Dragon Fire"
is_special = true