["tavern_quest_notice_event"]
kind = "StoryEvent/v1"
progress_trigger = 0
event_type = "ENCOUNTER"
encounter_id = "tavern_quest_notice"
# enemy_id = None
# dungeon_id = None
messages = [
    "{party_name} gathers around the fire at a local tavern when a rider delivers a notice to the bar keep",
    "the notice reads:",
    "His Highness King Stallman has requested all who favor themselves brave warriors present themselves at the Open Hall as the king has a task which requires great courage for them to undertake.",
    "After seeing the kings missive the path ahead is clear.",
    ]
success_messages = [
  "And thus {party_name} began their quest.",
  "If only they knew the trials and triumphs that lay ahead..."
]
failure_messages = []


["meet_the_king_event"]
kind = "StoryEvent/v1"
progress_trigger = 25
event_type = "ENCOUNTER"
encounter_id = "meet_the_king"
# enemy_id = None
# dungeon_id = None
messages = [
    "{party_name} is welcomed at the Open Hall by King Stallman",
    "Upon arrival the King tells you of the dark rumours which have recently been confirmed to him.",
    "",
    "The dark wizard Algolon is working to resurrect an ancient evil from the dead.",
    "The exact location of this is unknown.",
    "Rumors say that outside the town of Debina on the wizard Cobolus, a known collaborator of Algolon has been sighted.",
    "The king asks this great task of {party_name}, go forth and find Cobolus, attempt to ascertain the whereabouts of Algolon and where he plans to carry out this ritual."
]
success_messages = [
  "{party_name} is are fully rested and have a full stock of potions", "And thus {party_name} began their quest.",
  "If only they knew the trials and triumphs that lay ahead..."]
failure_messages = []

["battle_cobolus"]
progress_trigger = 50
kind = "StoryEvent/v1"
event_type = "BOSS_ENCOUNTER"
# encounter_id = None
enemy_id = "midway_boss"
# dungeon_id = None
messages = [
  "On the outskirts of Debina, you find the lair of Cobolus and engage him in combat."
]
success_messages = [
  "Defeated, Cobolus lays near death, but just as you approach to begin interrogating him a flash of purple light blinds you, and a massive explosion knocks you backwards. When the dust and smoke clear, you see the charred remains of the once mighty wizard, smoking as the smell of ash and burning flesh fills the air.",
  "Despite your best efforts to examine his lair you find no conclusive path to Algolon, however you do find a half ruined map with markings on indicating the location of a fortress deep in the mountains that may offer some clues."
]
failure_messages = [
  "As the the corpses of {party_name}, lay limp on the cold ground the Cobolus begins an ancient and evil incantation",
  "As their bodies begin to stir from the sleep of death, Cobolus's face turns to an evil grin as he with is new band of undead minions venture deep into his lair..."
]

["algolons_fortress_encounter"]
progress_trigger = 75
event_type = "DUNGEON_ENCOUNTER"
kind = "StoryEvent/v1"
# encounter_id = None
# enemy_id = None
dungeon_id = "algolons_fortress"
messages = [
  "Deep in the mountains you arrive at the Fortress, the air is still and the world silent, no sign of a living thing can be heard or seen, save for the faint trails of smoke escaping from the depths of fortress.",
  "The cold winds whirl around {party_name} as they move forward towards the fortress"
]
success_messages = [
  "With his dying breath, Algolon's arch mage sputters out 'It is to late, far to late, my master will complete his work with or without me, the is nothing you can do'",
  "The wizard's body goes limp, and his flesh turns to ash leaving a blacked skelton draped in blood-soaked robes..."
]
failure_messages = [
  "As the last member of {party_name} falls, Algolon's arch mage cackles a sinister laugh, as his minions gather the corpses and haul them away for their dark experiments ",
  "Algolon's arch mage turns and begins his accent to the summit of Godsblood peak where his master, and the great evil he is summoning, await."
]

